// This is automatically generated by CodeBind. Please do not modify it.

namespace CodeBind.Demo
{
    public partial class TestMono
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Transform m_TestTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Animator m_TestAnimator;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject m_Test2GameObject;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Transform m_Test2Transform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Animator m_Test2Animator;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private CodeBind.CSCodeBindMono m_TestCSCodeBindMono;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private CodeBind.ReferenceBindMono m_TestReferenceBindMono;

        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Animator[] m_Test2AnimatorArray;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.GameObject[] m_Test2GameObjectArray;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Transform[] m_Test2TransformArray;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Animator[] m_TestAnimatorArray;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Transform[] m_TestTransformArray;

        public UnityEngine.Transform TestTransform => m_TestTransform;
        public UnityEngine.Animator TestAnimator => m_TestAnimator;
        public UnityEngine.GameObject Test2GameObject => m_Test2GameObject;
        public UnityEngine.Transform Test2Transform => m_Test2Transform;
        public UnityEngine.Animator Test2Animator => m_Test2Animator;
        public CodeBind.CSCodeBindMono TestCSCodeBindMono => m_TestCSCodeBindMono;
        public CodeBind.ReferenceBindMono TestReferenceBindMono => m_TestReferenceBindMono;

        public UnityEngine.Animator[] Test2AnimatorArray => m_Test2AnimatorArray;
        public UnityEngine.GameObject[] Test2GameObjectArray => m_Test2GameObjectArray;
        public UnityEngine.Transform[] Test2TransformArray => m_Test2TransformArray;
        public UnityEngine.Animator[] TestAnimatorArray => m_TestAnimatorArray;
        public UnityEngine.Transform[] TestTransformArray => m_TestTransformArray;

    }
}
