// This is automatically generated by CodeBind. Please do not modify it.

public partial class TestCS : CodeBind.ICSCodeBind
{
    public CodeBind.CSCodeBindMono BindMono { get; private set; }
    public UnityEngine.Transform CachedTransform { get; private set; }

    public UnityEngine.Transform SelfTransform { get; private set; }
    public UnityEngine.Animation OtherAnimation { get; private set; }

    public UnityEngine.Animation[] ListAnimationArray { get; private set; }

    public void InitBind(CodeBind.CSCodeBindMono mono)
    {
        this.BindMono = mono;
        this.CachedTransform = mono.transform;
        this.SelfTransform = this.BindMono.BindComponents[0] as UnityEngine.Transform;
        this.OtherAnimation = this.BindMono.BindComponents[1] as UnityEngine.Animation;
        this.ListAnimationArray = new UnityEngine.Animation[4]
        {
            this.BindMono.BindComponents[2] as UnityEngine.Animation,
            this.BindMono.BindComponents[3] as UnityEngine.Animation,
            this.BindMono.BindComponents[4] as UnityEngine.Animation,
            this.BindMono.BindComponents[5] as UnityEngine.Animation,
        };
    }

    public void ClearBind()
    {
        this.BindMono = null;
        this.CachedTransform = null;
        this.SelfTransform = null;
        this.OtherAnimation = null;
        this.ListAnimationArray = null;
    }
}
