// This is automatically generated by CodeBind. Please do not modify it.

public partial class TestCS : CodeBind.IPlainClassBinding
{
    public CodeBind.PlainClassBindingHost BindingHost { get; private set; }
    public UnityEngine.Transform RootTransform { get; private set; }

    public UnityEngine.Transform SelfTransform { get; private set; }
    public UnityEngine.Animation OtherAnimation { get; private set; }

    public UnityEngine.Animation[] ListAnimationArray { get; private set; }

    public void Bind(CodeBind.PlainClassBindingHost host)
    {
        this.BindingHost = host;
        this.RootTransform = host.transform;
        this.SelfTransform = this.BindingHost.BindingTargets[0] as UnityEngine.Transform;
        this.OtherAnimation = this.BindingHost.BindingTargets[1] as UnityEngine.Animation;
        this.ListAnimationArray = new UnityEngine.Animation[4]
        {
            this.BindingHost.BindingTargets[2] as UnityEngine.Animation,
            this.BindingHost.BindingTargets[3] as UnityEngine.Animation,
            this.BindingHost.BindingTargets[4] as UnityEngine.Animation,
            this.BindingHost.BindingTargets[5] as UnityEngine.Animation,
        };
    }

    public void Unbind()
    {
        this.BindingHost = null;
        this.RootTransform = null;
        this.SelfTransform = null;
        this.OtherAnimation = null;
        this.ListAnimationArray = null;
    }
}
