// This is automatically generated by CodeBind. Please do not modify it.

public partial class TestCS : CodeBind.ICSCodeBind
{
    public CodeBind.CSCodeBindMono Mono { get; private set; }
    public UnityEngine.Transform Transform { get; private set; }

    public UnityEngine.Transform SelfTransform { get; private set; }
    public UnityEngine.Animation OtherAnimation { get; private set; }

    public UnityEngine.Animation[] ListAnimationArray { get; private set; }

    public void InitBind(CodeBind.CSCodeBindMono mono)
    {
        Mono = mono;
        Transform = mono.transform;
        SelfTransform = Mono.BindComponents[0] as UnityEngine.Transform;
        OtherAnimation = Mono.BindComponents[1] as UnityEngine.Animation;
        ListAnimationArray = new UnityEngine.Animation[4]
        {
            Mono.BindComponents[2] as UnityEngine.Animation,
            Mono.BindComponents[3] as UnityEngine.Animation,
            Mono.BindComponents[4] as UnityEngine.Animation,
            Mono.BindComponents[5] as UnityEngine.Animation,
        };
    }

    public void ClearBind()
    {
        Mono = null;
        Transform = null;
        SelfTransform = null;
        OtherAnimation = null;
        ListAnimationArray = null;
    }
}
