using System.Collections.Generic;
using System.Text;

namespace CodeBind.Editor
{
    internal static class BindingSourceBuilder
    {
        internal static string BuildMonoBehaviourBindingSource(string namespaceName, string className, List<BindingDescriptor> singleBindings, SortedDictionary<string, List<BindingDescriptor>> arrayBindingsByMemberName)
        {
            StringBuilder sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// This is automatically generated by CodeBind. Please do not modify it.");
            sourceBuilder.AppendLine("");
            string indentation = string.Empty;
            bool hasNamespace = !string.IsNullOrEmpty(namespaceName);
            if (hasNamespace)
            {
                sourceBuilder.AppendLine($"namespace {namespaceName}");
                sourceBuilder.AppendLine("{");
                indentation = "\t";
            }
            sourceBuilder.AppendLine($"{indentation}public partial class {className}");
            sourceBuilder.AppendLine($"{indentation}{{");
            foreach (BindingDescriptor binding in singleBindings)
            {
                sourceBuilder.AppendLine($"{indentation}\t[UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup(\"Binding Targets\"), Sirenix.OdinInspector.ReadOnly]");
                sourceBuilder.AppendLine($"{indentation}\tprivate {binding.TargetType.FullName} {BindingCodeCustomizerRegistry.GetSerializedFieldName(binding.MemberNamePrefix, binding.TargetToken)};");
            }
            foreach (KeyValuePair<string, List<BindingDescriptor>> kv in arrayBindingsByMemberName)
            {
                BindingDescriptor binding = kv.Value[0];
                sourceBuilder.AppendLine($"{indentation}\t[UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup(\"Binding Targets\"), Sirenix.OdinInspector.ReadOnly]");
                sourceBuilder.AppendLine($"{indentation}\tprivate {binding.TargetType.FullName}[] {BindingCodeCustomizerRegistry.GetSerializedArrayFieldName(binding.MemberNamePrefix, binding.TargetToken)};");
            }
            sourceBuilder.AppendLine("");
            foreach (BindingDescriptor binding in singleBindings)
            {
                sourceBuilder.AppendLine($"{indentation}\tpublic {binding.TargetType.FullName} {BindingCodeCustomizerRegistry.GetPublicPropertyName(binding.MemberNamePrefix, binding.TargetToken)} => this.{BindingCodeCustomizerRegistry.GetSerializedFieldName(binding.MemberNamePrefix, binding.TargetToken)};");
            }
            foreach (KeyValuePair<string, List<BindingDescriptor>> kv in arrayBindingsByMemberName)
            {
                BindingDescriptor binding = kv.Value[0];
                sourceBuilder.AppendLine($"{indentation}\tpublic {binding.TargetType.FullName}[] {BindingCodeCustomizerRegistry.GetPublicArrayPropertyName(binding.MemberNamePrefix, binding.TargetToken)} => this.{BindingCodeCustomizerRegistry.GetSerializedArrayFieldName(binding.MemberNamePrefix, binding.TargetToken)};");
            }
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine("#if UNITY_EDITOR");
            sourceBuilder.AppendLine($"{indentation}\t[Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]");
            sourceBuilder.AppendLine($"{indentation}\tprivate void DrawMissingTargetsWarning()");
            sourceBuilder.AppendLine($"{indentation}\t{{");
            sourceBuilder.AppendLine($"{indentation}\t\tSirenix.Utilities.Editor.SirenixEditorGUI.MessageBox(\"Binding targets contain missing references.\", UnityEditor.MessageType.Warning);");
            sourceBuilder.AppendLine($"{indentation}\t}}");
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine($"{indentation}\tprivate bool HasMissingTargets()");
            sourceBuilder.AppendLine($"{indentation}\t{{");
            foreach (BindingDescriptor binding in singleBindings)
            {
                sourceBuilder.AppendLine($"{indentation}\t\tif (this.{BindingCodeCustomizerRegistry.GetSerializedFieldName(binding.MemberNamePrefix, binding.TargetToken)} == null) return true;");
            }
            foreach (KeyValuePair<string, List<BindingDescriptor>> kv in arrayBindingsByMemberName)
            {
                BindingDescriptor binding = kv.Value[0];
                string arrayFieldName = BindingCodeCustomizerRegistry.GetSerializedArrayFieldName(binding.MemberNamePrefix, binding.TargetToken);
                sourceBuilder.AppendLine($"{indentation}\t\tif (this.{arrayFieldName} == null || this.{arrayFieldName}.Length == 0) return true;");
                sourceBuilder.AppendLine($"{indentation}\t\tfor (int i = 0; i < this.{arrayFieldName}.Length; i++)");
                sourceBuilder.AppendLine($"{indentation}\t\t\tif (this.{arrayFieldName}[i] == null) return true;");
            }
            sourceBuilder.AppendLine($"{indentation}\t\treturn false;");
            sourceBuilder.AppendLine($"{indentation}\t}}");
            sourceBuilder.AppendLine("#endif");
            sourceBuilder.AppendLine("");
            sourceBuilder.Append(BindingCodeCustomizerRegistry.BuildAdditionalSource(namespaceName, className, singleBindings, arrayBindingsByMemberName, $"{indentation}\t"));
            sourceBuilder.AppendLine($"{indentation}}}");
            if (hasNamespace)
            {
                sourceBuilder.AppendLine("}");
            }
            return sourceBuilder.ToString();
        }

        internal static string BuildPlainClassBindingSource(string namespaceName, string className, List<BindingDescriptor> singleBindings, SortedDictionary<string, List<BindingDescriptor>> arrayBindingsByMemberName, List<BindingDescriptor> arrayBindingElements)
        {
            StringBuilder sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// This is automatically generated by CodeBind. Please do not modify it.");
            sourceBuilder.AppendLine("");
            string indentation = string.Empty;
            bool hasNamespace = !string.IsNullOrEmpty(namespaceName);
            if (hasNamespace)
            {
                sourceBuilder.AppendLine($"namespace {namespaceName}");
                sourceBuilder.AppendLine("{");
                indentation = "\t";
            }
            sourceBuilder.AppendLine($"{indentation}public partial class {className} : CodeBind.IPlainClassBinding");
            sourceBuilder.AppendLine($"{indentation}{{");
            sourceBuilder.AppendLine($"{indentation}\tpublic CodeBind.PlainClassBindingHost BindingHost {{ get; private set; }}");
            sourceBuilder.AppendLine($"{indentation}\tpublic UnityEngine.Transform RootTransform {{ get; private set; }}");
            sourceBuilder.AppendLine("");
            foreach (BindingDescriptor binding in singleBindings)
            {
                sourceBuilder.AppendLine($"{indentation}\tpublic {binding.TargetType.FullName} {BindingCodeCustomizerRegistry.GetPublicPropertyName(binding.MemberNamePrefix, binding.TargetToken)} {{ get; private set; }}");
            }
            foreach (KeyValuePair<string, List<BindingDescriptor>> kv in arrayBindingsByMemberName)
            {
                BindingDescriptor binding = kv.Value[0];
                sourceBuilder.AppendLine($"{indentation}\tpublic {binding.TargetType.FullName}[] {BindingCodeCustomizerRegistry.GetPublicArrayPropertyName(binding.MemberNamePrefix, binding.TargetToken)} {{ get; private set; }}");
            }
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine($"{indentation}\tpublic void Bind(CodeBind.PlainClassBindingHost host)");
            sourceBuilder.AppendLine($"{indentation}\t{{");
            sourceBuilder.AppendLine($"{indentation}\t\tthis.BindingHost = host;");
            sourceBuilder.AppendLine($"{indentation}\t\tthis.RootTransform = host.transform;");
            for (int i = 0; i < singleBindings.Count; i++)
            {
                BindingDescriptor binding = singleBindings[i];
                sourceBuilder.AppendLine($"{indentation}\t\tthis.{BindingCodeCustomizerRegistry.GetPublicPropertyName(binding.MemberNamePrefix, binding.TargetToken)} = this.BindingHost.BindingTargets[{i}] as {binding.TargetType.FullName};");
            }
            foreach (KeyValuePair<string, List<BindingDescriptor>> kv in arrayBindingsByMemberName)
            {
                BindingDescriptor firstArrayBinding = kv.Value[0];
                sourceBuilder.AppendLine($"{indentation}\t\tthis.{BindingCodeCustomizerRegistry.GetPublicArrayPropertyName(firstArrayBinding.MemberNamePrefix, firstArrayBinding.TargetToken)} = new {firstArrayBinding.TargetType.FullName}[{kv.Value.Count}]");
                sourceBuilder.AppendLine($"{indentation}\t\t{{");
                for (int i = 0; i < kv.Value.Count; i++)
                {
                    BindingDescriptor binding = kv.Value[i];
                    sourceBuilder.AppendLine($"{indentation}\t\t\tthis.BindingHost.BindingTargets[{arrayBindingElements.IndexOf(binding) + singleBindings.Count}] as {binding.TargetType.FullName},");
                }
                sourceBuilder.AppendLine($"{indentation}\t\t}};");
            }
            sourceBuilder.AppendLine($"{indentation}\t}}");
            sourceBuilder.AppendLine("");
            sourceBuilder.AppendLine($"{indentation}\tpublic void Unbind()");
            sourceBuilder.AppendLine($"{indentation}\t{{");
            sourceBuilder.AppendLine($"{indentation}\t\tthis.BindingHost = null;");
            sourceBuilder.AppendLine($"{indentation}\t\tthis.RootTransform = null;");
            for (int i = 0; i < singleBindings.Count; i++)
            {
                BindingDescriptor binding = singleBindings[i];
                sourceBuilder.AppendLine($"{indentation}\t\tthis.{BindingCodeCustomizerRegistry.GetPublicPropertyName(binding.MemberNamePrefix, binding.TargetToken)} = null;");
            }
            foreach (KeyValuePair<string, List<BindingDescriptor>> kv in arrayBindingsByMemberName)
            {
                BindingDescriptor binding = kv.Value[0];
                sourceBuilder.AppendLine($"{indentation}\t\tthis.{BindingCodeCustomizerRegistry.GetPublicArrayPropertyName(binding.MemberNamePrefix, binding.TargetToken)} = null;");
            }
            sourceBuilder.AppendLine($"{indentation}\t}}");
            sourceBuilder.AppendLine("");
            sourceBuilder.Append(BindingCodeCustomizerRegistry.BuildAdditionalSource(namespaceName, className, singleBindings, arrayBindingsByMemberName, $"{indentation}\t"));
            sourceBuilder.AppendLine($"{indentation}}}");
            if (hasNamespace)
            {
                sourceBuilder.AppendLine("}");
            }
            return sourceBuilder.ToString();
        }
    }
}
