using System.Collections.Generic;
using System.Text;

namespace CodeBind.Editor
{
    internal static class CodeHelper
    {
        internal static string GetMonoBindCodeString(string nameSpace, string className, List<CodeBindData> bindDatas, SortedDictionary<string, List<CodeBindData>> bindArrayDataDict)
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// This is automatically generated by CodeBind. Please do not modify it.");
            stringBuilder.AppendLine("");
            string indentation = string.Empty;
            bool needNameSpace = !string.IsNullOrEmpty(nameSpace);
            //命名空间
            if (needNameSpace)
            {
                stringBuilder.AppendLine($"namespace {nameSpace}");
                stringBuilder.AppendLine("{");
                indentation = "\t";
            }
            //类名
            stringBuilder.AppendLine($"{indentation}public partial class {className}");
            stringBuilder.AppendLine($"{indentation}{{");
            //组件字段
            foreach (CodeBindData bindData in bindDatas)
            {
                stringBuilder.AppendLine($"{indentation}\t[UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup(\"BindData\"), Sirenix.OdinInspector.ReadOnly]");
                stringBuilder.AppendLine($"{indentation}\tprivate {bindData.BindType.FullName} m_{bindData.BindName}{bindData.BindPrefix};");
            }
            stringBuilder.AppendLine("");
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                stringBuilder.AppendLine($"{indentation}\t[UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup(\"BindData\"), Sirenix.OdinInspector.ReadOnly]");
                stringBuilder.AppendLine($"{indentation}\tprivate {kv.Value[0].BindType.FullName}[] m_{kv.Key}Array;");
            }
            stringBuilder.AppendLine("");
            foreach (CodeBindData bindData in bindDatas)
            {
                stringBuilder.AppendLine($"{indentation}\tpublic {bindData.BindType.FullName} {bindData.BindName}{bindData.BindPrefix} => m_{bindData.BindName}{bindData.BindPrefix};");
            }
            stringBuilder.AppendLine("");
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                stringBuilder.AppendLine($"{indentation}\tpublic {kv.Value[0].BindType.FullName}[] {kv.Key}Array => m_{kv.Key}Array;");
            }
            stringBuilder.AppendLine("");
#if STATE_CONTROLLER_CODE_BIND
            //StateController
            Type stateControllerMonoType = typeof(StateController.StateControllerMono);
            if (CodeBindNameTypeCollection.BindTypeNameDict.TryGetValue(stateControllerMonoType, out string prefix))
            {
                foreach (CodeBindData bindData in bindDatas)
                {
                    if (bindData.BindType == stateControllerMonoType)
                    {
                        var controller = bindData.BindTransform.GetComponent<StateController.StateControllerMono>();
                        foreach (var data in controller.EditorControllerDatas)
                        {
                            stringBuilder.AppendLine($"{indentation}\tprivate StateController.StateControllerData m_{bindData.BindName}{data.Name}StateControllerData;");
                            stringBuilder.AppendLine($"{indentation}\tpublic StateController.StateControllerData {bindData.BindName}{data.Name}StateControllerData => m_{bindData.BindName}{data.Name}StateControllerData ??= {bindData.BindName}{bindData.BindPrefix}.GetData(\"{data.Name}\");");
                            stringBuilder.AppendLine($"{indentation}\tpublic static class {bindData.BindName}{data.Name}StateName");
                            stringBuilder.AppendLine($"{indentation}\t{{");
                            foreach (var stateName in data.StateNames)
                            {
                                stringBuilder.AppendLine($"{indentation}\t\tpublic const string {stateName} = \"{stateName}\";");
                            }
                            stringBuilder.AppendLine($"{indentation}\t}}");
                        }
                        stringBuilder.AppendLine("");
                    }
                }
            }
#endif
            stringBuilder.AppendLine($"{indentation}}}");
            if (needNameSpace)
            {
                stringBuilder.AppendLine("}");
            }
            return stringBuilder.ToString();
        }
        
        internal static string GetCSBindCodeString(string nameSpace, string className, List<CodeBindData> bindDatas, SortedDictionary<string, List<CodeBindData>> bindArrayDataDict, List<CodeBindData> bindArrayDatas)
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// This is automatically generated by CodeBind. Please do not modify it.");
            stringBuilder.AppendLine("");
            string indentation = string.Empty;
            bool needNameSpace = !string.IsNullOrEmpty(nameSpace);
            //命名空间
            if (needNameSpace)
            {
                stringBuilder.AppendLine($"namespace {nameSpace}");
                stringBuilder.AppendLine("{");
                indentation = "\t";
            }
            //类名
            stringBuilder.AppendLine($"{indentation}public partial class {className} : CodeBind.ICSCodeBind");
            stringBuilder.AppendLine($"{indentation}{{");
            //组件字段
            stringBuilder.AppendLine($"{indentation}\tpublic CodeBind.CSCodeBindMono Mono {{ get; private set; }}");
            stringBuilder.AppendLine($"{indentation}\tpublic UnityEngine.Transform Transform {{ get; private set; }}");
            stringBuilder.AppendLine("");
            foreach (CodeBindData bindData in bindDatas)
            {
                stringBuilder.AppendLine($"{indentation}\tpublic {bindData.BindType.FullName} {bindData.BindName}{bindData.BindPrefix} {{ get; private set; }}");
            }
            stringBuilder.AppendLine("");
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                stringBuilder.AppendLine($"{indentation}\tpublic {kv.Value[0].BindType.FullName}[] {kv.Key}Array {{ get; private set; }}");
            }
            stringBuilder.AppendLine("");
#if STATE_CONTROLLER_CODE_BIND
            //StateController
            Type stateControllerMonoType = typeof(StateController.StateControllerMono);
            if (CodeBindNameTypeCollection.BindTypeNameDict.TryGetValue(stateControllerMonoType, out string prefix))
            {
                foreach (CodeBindData bindData in bindDatas)
                {
                    if (bindData.BindType == stateControllerMonoType)
                    {
                        var controller = bindData.BindTransform.GetComponent<StateController.StateControllerMono>();
                        foreach (var data in controller.EditorControllerDatas)
                        {
                            stringBuilder.AppendLine($"{indentation}\tprivate StateController.StateControllerData m_{bindData.BindName}{data.Name}StateControllerData;");
                            stringBuilder.AppendLine($"{indentation}\tpublic StateController.StateControllerData {bindData.BindName}{data.Name}StateControllerData => m_{bindData.BindName}{data.Name}StateControllerData ??= {bindData.BindName}{bindData.BindPrefix}.GetData(\"{data.Name}\");");
                            stringBuilder.AppendLine($"{indentation}\tpublic static class {bindData.BindName}{data.Name}StateName");
                            stringBuilder.AppendLine($"{indentation}\t{{");
                            foreach (var stateName in data.StateNames)
                            {
                                stringBuilder.AppendLine($"{indentation}\t\tpublic const string {stateName} = \"{stateName}\";");
                            }
                            stringBuilder.AppendLine($"{indentation}\t}}");
                        }
                        stringBuilder.AppendLine("");
                    }
                }
            }
#endif
            //InitBind方法
            stringBuilder.AppendLine($"{indentation}\tpublic void InitBind(CodeBind.CSCodeBindMono mono)");
            stringBuilder.AppendLine($"{indentation}\t{{");
            stringBuilder.AppendLine($"{indentation}\t\tMono = mono;");
            stringBuilder.AppendLine($"{indentation}\t\tTransform = mono.transform;");
            for (int i = 0; i < bindDatas.Count; i++)
            {
                CodeBindData bindData = bindDatas[i];
                stringBuilder.AppendLine($"{indentation}\t\t{bindData.BindName}{bindData.BindPrefix} = Mono.BindComponents[{i}] as {bindData.BindType.FullName};");
            }
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                stringBuilder.AppendLine($"{indentation}\t\t{kv.Key}Array = new {kv.Value[0].BindType.FullName}[{kv.Value.Count}]");
                stringBuilder.AppendLine($"{indentation}\t\t{{");
                for (int i = 0; i < kv.Value.Count; i++)
                {
                    CodeBindData bindData = kv.Value[i];
                    stringBuilder.AppendLine($"{indentation}\t\t\tMono.BindComponents[{bindArrayDatas.IndexOf(bindData) + bindDatas.Count}] as {bindData.BindType.FullName},");
                }
                stringBuilder.AppendLine($"{indentation}\t\t}};");
            }
            stringBuilder.AppendLine($"{indentation}\t}}");
            //Clear方法
            stringBuilder.AppendLine("");
            stringBuilder.AppendLine($"{indentation}\tpublic void ClearBind()");
            stringBuilder.AppendLine($"{indentation}\t{{");
            stringBuilder.AppendLine($"{indentation}\t\tMono = null;");
            stringBuilder.AppendLine($"{indentation}\t\tTransform = null;");
            for (int i = 0; i < bindDatas.Count; i++)
            {
                CodeBindData bindData = bindDatas[i];
                stringBuilder.AppendLine($"{indentation}\t\t{bindData.BindName}{bindData.BindPrefix} = null;");
            }
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                stringBuilder.AppendLine($"{indentation}\t\t{kv.Key}Array = null;");
            }
            stringBuilder.AppendLine($"{indentation}\t}}");
            
            stringBuilder.AppendLine($"{indentation}}}");
            if (needNameSpace)
            {
                stringBuilder.AppendLine("}");
            }
            return stringBuilder.ToString();
        }
    }
}