using System.Collections.Generic;
using System.Text;

namespace CodeBind.Editor
{
    internal static class CodeHelper
    {
        internal static string GetMonoBindCodeString(string nameSpace, string className, List<CodeBindData> bindDatas, SortedDictionary<string, List<CodeBindData>> bindArrayDataDict)
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// This is automatically generated by CodeBind. Please do not modify it.");
            stringBuilder.AppendLine("");
            string indentation = string.Empty;
            bool needNameSpace = !string.IsNullOrEmpty(nameSpace);
            //命名空间
            if (needNameSpace)
            {
                stringBuilder.AppendLine($"namespace {nameSpace}");
                stringBuilder.AppendLine("{");
                indentation = "\t";
            }
            //类名
            stringBuilder.AppendLine($"{indentation}public partial class {className}");
            stringBuilder.AppendLine($"{indentation}{{");
            //组件字段
            foreach (CodeBindData bindData in bindDatas)
            {
                stringBuilder.AppendLine($"{indentation}\t[UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup(\"BindData\"), Sirenix.OdinInspector.ReadOnly]");
                stringBuilder.AppendLine($"{indentation}\tprivate {bindData.BindType.FullName} {CodeBindCustomizerCollection.GetFieldName(bindData.BindName, bindData.BindPrefix)};");
            }
            stringBuilder.AppendLine("");
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                CodeBindData bindData = kv.Value[0];
                stringBuilder.AppendLine($"{indentation}\t[UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup(\"BindData\"), Sirenix.OdinInspector.ReadOnly]");
                stringBuilder.AppendLine($"{indentation}\tprivate {bindData.BindType.FullName}[] {CodeBindCustomizerCollection.GetArrayFieldName(bindData.BindName, bindData.BindPrefix)};");
            }
            stringBuilder.AppendLine("");
            foreach (CodeBindData bindData in bindDatas)
            {
                stringBuilder.AppendLine($"{indentation}\tpublic {bindData.BindType.FullName} {CodeBindCustomizerCollection.GetPropertyName(bindData.BindName, bindData.BindPrefix)} => {CodeBindCustomizerCollection.GetFieldName(bindData.BindName, bindData.BindPrefix)};");
            }
            stringBuilder.AppendLine("");
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                CodeBindData bindData = kv.Value[0];
                stringBuilder.AppendLine($"{indentation}\tpublic {bindData.BindType.FullName}[] {CodeBindCustomizerCollection.GetArrayPropertyName(bindData.BindName, bindData.BindPrefix)} => {CodeBindCustomizerCollection.GetArrayFieldName(bindData.BindName, bindData.BindPrefix)};");
            }
            stringBuilder.AppendLine("");
            //额外生成代码
            stringBuilder.Append(CodeBindCustomizerCollection.GenerateExtraCode(nameSpace, className, bindDatas, bindArrayDataDict, $"{indentation}\t"));
            //CheckBindDataExitEmpty方法
            stringBuilder.AppendLine("#if UNITY_EDITOR");
            stringBuilder.AppendLine($"{indentation}\t[Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]");
            stringBuilder.AppendLine($"{indentation}\t[Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]");
            stringBuilder.AppendLine($"{indentation}\t[Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]");
            stringBuilder.AppendLine($"{indentation}\tprivate string BindDataExitEmptyWarning => \"BindData contains empty reference, please check.\";");
            stringBuilder.AppendLine("");
            stringBuilder.AppendLine($"{indentation}\tprivate bool CheckBindDataExitEmpty()");
            stringBuilder.AppendLine($"{indentation}\t{{");
            foreach (CodeBindData bindData in bindDatas)
            {
                stringBuilder.AppendLine($"{indentation}\t\tif (this.{CodeBindCustomizerCollection.GetFieldName(bindData.BindName, bindData.BindPrefix)} == null) return true;");
            }
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                CodeBindData bindData = kv.Value[0];
                string arrayFieldName = CodeBindCustomizerCollection.GetArrayFieldName(bindData.BindName, bindData.BindPrefix);
                stringBuilder.AppendLine($"{indentation}\t\tif (this.{arrayFieldName} == null || this.{arrayFieldName}.Length == 0) return true;");
                stringBuilder.AppendLine($"{indentation}\t\tfor (int i = 0; i < this.{arrayFieldName}.Length; i++)");
                stringBuilder.AppendLine($"{indentation}\t\t\tif (this.{arrayFieldName}[i] == null) return true;");
            }
            stringBuilder.AppendLine($"{indentation}\t\treturn false;");
            stringBuilder.AppendLine($"{indentation}\t}}");
            stringBuilder.AppendLine("#endif");

            stringBuilder.AppendLine($"{indentation}}}");
            if (needNameSpace)
            {
                stringBuilder.AppendLine("}");
            }
            return stringBuilder.ToString();
        }
        
        internal static string GetCSBindCodeString(string nameSpace, string className, List<CodeBindData> bindDatas, SortedDictionary<string, List<CodeBindData>> bindArrayDataDict, List<CodeBindData> bindArrayDatas)
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// This is automatically generated by CodeBind. Please do not modify it.");
            stringBuilder.AppendLine("");
            string indentation = string.Empty;
            bool needNameSpace = !string.IsNullOrEmpty(nameSpace);
            //命名空间
            if (needNameSpace)
            {
                stringBuilder.AppendLine($"namespace {nameSpace}");
                stringBuilder.AppendLine("{");
                indentation = "\t";
            }
            //类名
            stringBuilder.AppendLine($"{indentation}public partial class {className} : CodeBind.ICSCodeBind");
            stringBuilder.AppendLine($"{indentation}{{");
            //组件字段
            stringBuilder.AppendLine($"{indentation}\tpublic CodeBind.CSCodeBindMono Mono {{ get; private set; }}");
            stringBuilder.AppendLine($"{indentation}\tpublic UnityEngine.Transform Transform {{ get; private set; }}");
            stringBuilder.AppendLine("");
            foreach (CodeBindData bindData in bindDatas)
            {
                stringBuilder.AppendLine($"{indentation}\tpublic {bindData.BindType.FullName} {CodeBindCustomizerCollection.GetPropertyName(bindData.BindName, bindData.BindPrefix)} {{ get; private set; }}");
            }
            stringBuilder.AppendLine("");
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                CodeBindData bindData = kv.Value[0];
                stringBuilder.AppendLine($"{indentation}\tpublic {bindData.BindType.FullName}[] {CodeBindCustomizerCollection.GetArrayPropertyName(bindData.BindName, bindData.BindPrefix)} {{ get; private set; }}");
            }
            stringBuilder.AppendLine("");
            //InitBind方法
            stringBuilder.AppendLine($"{indentation}\tpublic void InitBind(CodeBind.CSCodeBindMono mono)");
            stringBuilder.AppendLine($"{indentation}\t{{");
            stringBuilder.AppendLine($"{indentation}\t\tMono = mono;");
            stringBuilder.AppendLine($"{indentation}\t\tTransform = mono.transform;");
            for (int i = 0; i < bindDatas.Count; i++)
            {
                CodeBindData bindData = bindDatas[i];
                stringBuilder.AppendLine($"{indentation}\t\t{CodeBindCustomizerCollection.GetPropertyName(bindData.BindName, bindData.BindPrefix)} = Mono.BindComponents[{i}] as {bindData.BindType.FullName};");
            }
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                CodeBindData firstBindData = kv.Value[0];
                stringBuilder.AppendLine($"{indentation}\t\t{CodeBindCustomizerCollection.GetArrayPropertyName(firstBindData.BindName, firstBindData.BindPrefix)} = new {firstBindData.BindType.FullName}[{kv.Value.Count}]");
                stringBuilder.AppendLine($"{indentation}\t\t{{");
                for (int i = 0; i < kv.Value.Count; i++)
                {
                    CodeBindData bindData = kv.Value[i];
                    stringBuilder.AppendLine($"{indentation}\t\t\tMono.BindComponents[{bindArrayDatas.IndexOf(bindData) + bindDatas.Count}] as {bindData.BindType.FullName},");
                }
                stringBuilder.AppendLine($"{indentation}\t\t}};");
            }
            stringBuilder.AppendLine($"{indentation}\t}}");
            //Clear方法
            stringBuilder.AppendLine("");
            stringBuilder.AppendLine($"{indentation}\tpublic void ClearBind()");
            stringBuilder.AppendLine($"{indentation}\t{{");
            stringBuilder.AppendLine($"{indentation}\t\tMono = null;");
            stringBuilder.AppendLine($"{indentation}\t\tTransform = null;");
            for (int i = 0; i < bindDatas.Count; i++)
            {
                CodeBindData bindData = bindDatas[i];
                stringBuilder.AppendLine($"{indentation}\t\t{CodeBindCustomizerCollection.GetPropertyName(bindData.BindName, bindData.BindPrefix)} = null;");
            }
            foreach (KeyValuePair<string, List<CodeBindData>> kv in bindArrayDataDict)
            {
                CodeBindData bindData = kv.Value[0];
                stringBuilder.AppendLine($"{indentation}\t\t{CodeBindCustomizerCollection.GetArrayPropertyName(bindData.BindName, bindData.BindPrefix)} = null;");
            }
            stringBuilder.AppendLine($"{indentation}\t}}");
            //额外生成代码
            stringBuilder.Append(CodeBindCustomizerCollection.GenerateExtraCode(nameSpace, className, bindDatas, bindArrayDataDict, $"{indentation}\t"));
            stringBuilder.AppendLine($"{indentation}}}");
            if (needNameSpace)
            {
                stringBuilder.AppendLine("}");
            }
            return stringBuilder.ToString();
        }
    }
}
