using System;
using System.Collections.Generic;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace CodeBind.Editor
{
    internal sealed class CSCodeBinder : BaseCodeBinder
    {
        private readonly CSCodeBindMono m_CsCodeBindMono;
        
        public CSCodeBinder(MonoScript script, Transform rootTransform, char separatorChar): base(script, rootTransform, separatorChar)
        {
            m_CsCodeBindMono = rootTransform.GetComponent<CSCodeBindMono>();
            if (m_CsCodeBindMono == null)
            {
                throw new Exception($"PureCSCodeBinder init fail! {rootTransform} has no MonoBind!");
            }
        }

        protected override string GetGeneratorCode()
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// This is automatically generated by CodeBind. Please do not modify it.");
            stringBuilder.AppendLine("");
            string indentation = string.Empty;
            bool needNameSpace = !string.IsNullOrEmpty(m_ScriptNameSpace);
            //命名空间
            if (needNameSpace)
            {
                stringBuilder.AppendLine($"namespace {m_ScriptNameSpace}");
                stringBuilder.AppendLine("{");
                indentation = "\t";
            }
            //类名
            stringBuilder.AppendLine($"{indentation}public partial class {m_ScriptClassName} : CodeBind.ICSCodeBind");
            stringBuilder.AppendLine($"{indentation}{{");
            //组件字段
            stringBuilder.AppendLine($"{indentation}{indentation}public CodeBind.CSCodeBindMono Mono {{ get; private set; }}");
            stringBuilder.AppendLine($"{indentation}{indentation}public UnityEngine.Transform Transform {{ get; private set; }}");
            stringBuilder.AppendLine("");
            foreach (CodeBindData bindData in m_BindDatas)
            {
                stringBuilder.AppendLine($"{indentation}{indentation}public {bindData.BindType.FullName} {bindData.BindName}{bindData.BindPrefix} {{ get; private set; }}");
            }
            stringBuilder.AppendLine("");
            foreach (KeyValuePair<string, List<CodeBindData>> kv in m_BindArrayDataDict)
            {
                stringBuilder.AppendLine($"{indentation}{indentation}public {kv.Value[0].BindType.FullName}[] {kv.Key}Array {{ get; private set; }}");
            }
            stringBuilder.AppendLine("");
            //InitBind方法
            stringBuilder.AppendLine($"{indentation}{indentation}public void InitBind(CodeBind.CSCodeBindMono mono)");
            stringBuilder.AppendLine($"{indentation}{indentation}{{");
            stringBuilder.AppendLine($"{indentation}{indentation}{indentation}Mono = mono;");
            stringBuilder.AppendLine($"{indentation}{indentation}{indentation}Transform = mono.transform;");
            for (int i = 0; i < m_BindDatas.Count; i++)
            {
                CodeBindData bindData = m_BindDatas[i];
                stringBuilder.AppendLine($"{indentation}{indentation}{indentation}{bindData.BindName}{bindData.BindPrefix} = Mono.BindComponents[{i}] as {bindData.BindType.FullName};");
            }
            foreach (KeyValuePair<string, List<CodeBindData>> kv in m_BindArrayDataDict)
            {
                stringBuilder.AppendLine($"{indentation}{indentation}{indentation}{kv.Key}Array = new {kv.Value[0].BindType.FullName}[{kv.Value.Count}]");
                stringBuilder.AppendLine($"{indentation}{indentation}{indentation}{{");
                for (int i = 0; i < kv.Value.Count; i++)
                {
                    CodeBindData bindData = kv.Value[i];
                    stringBuilder.AppendLine($"{indentation}{indentation}{indentation}{indentation}Mono.BindComponents[{m_BindArrayDatas.IndexOf(bindData) + m_BindDatas.Count}] as {bindData.BindType.FullName},");
                }
                stringBuilder.AppendLine($"{indentation}{indentation}{indentation}}};");
            }
            stringBuilder.AppendLine($"{indentation}{indentation}}}");
            //Clear方法
            stringBuilder.AppendLine("");
            stringBuilder.AppendLine($"{indentation}{indentation}public void ClearBind()");
            stringBuilder.AppendLine($"{indentation}{indentation}{{");
            stringBuilder.AppendLine($"{indentation}{indentation}{indentation}Mono = null;");
            stringBuilder.AppendLine($"{indentation}{indentation}{indentation}Transform = null;");
            for (int i = 0; i < m_BindDatas.Count; i++)
            {
                CodeBindData bindData = m_BindDatas[i];
                stringBuilder.AppendLine($"{indentation}{indentation}{indentation}{bindData.BindName}{bindData.BindPrefix} = null;");
            }
            foreach (KeyValuePair<string, List<CodeBindData>> kv in m_BindArrayDataDict)
            {
                stringBuilder.AppendLine($"{indentation}{indentation}{indentation}{kv.Key}Array = null;");
            }
            stringBuilder.AppendLine($"{indentation}{indentation}}}");
            
            stringBuilder.AppendLine($"{indentation}}}");
            if (needNameSpace)
            {
                stringBuilder.AppendLine("}");
            }
            return stringBuilder.ToString();
        }

        protected override void SetSerialization()
        {
            List<string> bindNames = new List<string>();
            List<UnityEngine.Object> bindComponents = new List<UnityEngine.Object>();
            foreach (CodeBindData bindData in m_BindDatas)
            {
                bindNames.Add(bindData.BindName + bindData.BindPrefix);
                if(!TryGetBindTarget(bindData.BindTransform, bindData.BindType, out var target))
                {
                    throw new Exception($"Bind '{bindData.BindTransform} - {bindData.BindType}' fail!");
                }
                bindComponents.Add(target);
            }
            foreach (CodeBindData bindData in m_BindArrayDatas)
            {
                bindNames.Add($"{bindData.BindName}{bindData.BindPrefix}Array");
                if(!TryGetBindTarget(bindData.BindTransform, bindData.BindType, out var target))
                {
                    throw new Exception($"Bind '{bindData.BindTransform} - {bindData.BindType}' fail!");
                }
                bindComponents.Add(target);
            }
            m_CsCodeBindMono.SetBindComponents(bindNames.ToArray(), bindComponents.ToArray());
        }
    }
}
